--- !ditz.rubyforge.org,2008-03-06/project 
name: spiralweb
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: spiralweb
- !ditz.rubyforge.org,2008-03-06/component 
  name: Vim syntax file
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :released
  release_time: 2012-09-21 01:38:57.757479 Z
  log_events: 
  - - 2012-09-20 17:38:56.267936 Z
    - Michael McDermott <michael@zion>
    - created
    - First version released to the world.
  - - 2012-09-21 01:38:57.757487 Z
    - Michael McDermott <michael@zion>
    - released
    - Marking an old release complete.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.2
  status: :released
  release_time: 2012-10-08 03:54:02.819513 Z
  log_events: 
  - - 2012-09-20 17:39:14.798756 Z
    - Michael McDermott <michael@zion>
    - created
    - ""
  - - 2012-10-08 03:54:02.819533 Z
    - Michael McDermott <michael@zion>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.3
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-09-22 04:05:52.086774 Z
    - Michael McDermott <michael@zion>
    - created
    - ""
